import React, { useState, useEffect, useMemo } from 'react';
import {
  Download,
  Search,
  Eye,
  RotateCcw,
  TrendingUp,
  Receipt,
  ShoppingBag,
  CreditCard,
  Banknote,
  QrCode,
  Printer,
  Percent,
  Calendar,
  Tag,
  FolderOpen,
} from 'lucide-react';
import { api } from '../../lib/ipc';
import { formatCurrency, getTodayDateString, formatDateDMY, formatPaymentMethod } from '../../lib/format';
import { Header } from '../../components/Header';
import { Modal } from '../../components/Modal';
import { ReceiptPrintModal } from '../../components/ReceiptPrintModal';
import { CustomSelect } from '../../components/CustomSelect';
import { useSettings } from '../../contexts/SettingsContext';
import type { DashboardStats, Bill, BillDetail } from '../../types';
import toast from 'react-hot-toast';

export const ReportsPage: React.FC = () => {
  const { currencySymbol } = useSettings();
  const todayStr = getTodayDateString();
  const [dateFrom, setDateFrom] = useState(todayStr);
  const [dateTo, setDateTo] = useState(todayStr);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [paymentFilter, setPaymentFilter] = useState('');

  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [bills, setBills] = useState<Bill[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  // Detail Modal State
  const [selectedBillDetail, setSelectedBillDetail] = useState<BillDetail | null>(null);
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [isDetailLoading, setIsDetailLoading] = useState(false);
  const [isPrintModalOpen, setIsPrintModalOpen] = useState(false);

  const loadReport = async () => {
    setIsLoading(true);
    try {
      const [s, bList] = await Promise.all([
        api.getDashboardStats(dateFrom, dateTo).catch(() => null),
        api.getBills({ dateFrom, dateTo, page: 1, pageSize: 1000 }).catch(() => ({
          data: [],
          total: 0,
          page: 1,
          page_size: 1000,
          total_pages: 1,
        })),
      ]);
      setStats(
        s || {
          total_sales_paise: 0,
          total_bills: 0,
          total_items_sold: 0,
          cash_sales_paise: 0,
          upi_sales_paise: 0,
          card_sales_paise: 0,
          total_discount_paise: 0,
          total_gst_paise: 0,
          avg_bill_paise: 0,
        }
      );
      setBills(bList.data || []);
    } catch (err) {
      console.error('Report load error:', err);
      toast.error('Failed to generate report');
      setStats(null);
      setBills([]);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadReport();
  }, [dateFrom, dateTo]);

  // Export to Excel / CSV with UTF-8 BOM and immediate browser download
  const handleExportExcel = async () => {
    setIsExporting(true);
    try {
      // 1. Try backend server-side archive (Tauri native file save)
      try {
        if (dateFrom === dateTo) {
          await api.generateDailyReport(dateFrom);
        } else {
          await api.generateDateRangeReport(dateFrom, dateTo);
        }
      } catch (backendErr) {
        console.warn('Backend excel archiving not available or failed:', backendErr);
      }

      // 2. Client-side instant download of Excel-compatible CSV with UTF-8 BOM
      const targetBills = filteredBills.length > 0 ? filteredBills : bills;
      if (targetBills.length === 0) {
        toast.error('No sales records to export for selected dates');
        return;
      }

      const BOM = '\uFEFF';
      const lines: string[] = [];

      lines.push('"AESCION BILLING SOFTWARE - OFFICIAL SALES & TAX REGISTER"');
      lines.push(`"Report Period:","${formatDateDMY(dateFrom)} to ${formatDateDMY(dateTo)}"`);
      lines.push(`"Generated On:","${new Date().toLocaleTimeString()} on ${formatDateDMY(todayStr)}"`);
      lines.push(`"Generated By:","AESCION Automated Financial Ledger"`);
      lines.push('');

      // Summary KPI Section
      lines.push('"FINANCIAL SUMMARY"');
      lines.push(`"Total Bills:","${filteredTotals.count || targetBills.length}"`);
      lines.push(`"Gross Subtotal (${currencySymbol}):","${((filteredTotals.subtotalPaise || stats?.total_sales_paise || 0) / 100).toFixed(2)}"`);
      lines.push(`"Total Discounts Given (${currencySymbol}):","${((filteredTotals.discountPaise || stats?.total_discount_paise || 0) / 100).toFixed(2)}"`);
      lines.push(`"Total GST Collected (${currencySymbol}):","${((filteredTotals.gstPaise || stats?.total_gst_paise || 0) / 100).toFixed(2)}"`);
      lines.push(`"Net Grand Total Revenue (${currencySymbol}):","${((filteredTotals.grandTotalPaise || stats?.total_sales_paise || 0) / 100).toFixed(2)}"`);
      lines.push(`"Cash Sales (${currencySymbol}):","${((stats?.cash_sales_paise || 0) / 100).toFixed(2)}"`);
      lines.push(`"UPI Sales (${currencySymbol}):","${((stats?.upi_sales_paise || 0) / 100).toFixed(2)}"`);
      lines.push(`"Card Sales (${currencySymbol}):","${((stats?.card_sales_paise || 0) / 100).toFixed(2)}"`);
      lines.push('');

      // Itemized Register
      lines.push('"ITEMIZED SALES REGISTER"');
      const headers = [
        'Bill #',
        'Date (DD-MM-YYYY)',
        'Time',
        'Cashier',
        'Payment Method',
        `Subtotal (${currencySymbol})`,
        `Discount (${currencySymbol})`,
        `GST Total (${currencySymbol})`,
        `Grand Total (${currencySymbol})`,
        'Status'
      ];
      lines.push(headers.map(h => `"${h}"`).join(','));

      targetBills.forEach(b => {
        lines.push([
          `"#${b.bill_number}"`,
          `"${formatDateDMY(b.business_date)}"`,
          `"${b.bill_time}"`,
          `"${(b.user_name || 'Staff').replace(/"/g, '""')}"`,
          `"${(b.payment_method || 'Cash').toUpperCase()}"`,
          `"${(b.subtotal_paise / 100).toFixed(2)}"`,
          `"${(b.discount_amount_paise / 100).toFixed(2)}"`,
          `"${(b.gst_total_paise / 100).toFixed(2)}"`,
          `"${(b.grand_total_paise / 100).toFixed(2)}"`,
          `"${b.status.toUpperCase()}"`
        ].join(','));
      });

      // Grand totals row
      lines.push([
        '"TOTAL"',
        '""',
        '""',
        '""',
        '""',
        `"${(filteredTotals.subtotalPaise / 100).toFixed(2)}"`,
        `"${(filteredTotals.discountPaise / 100).toFixed(2)}"`,
        `"${(filteredTotals.gstPaise / 100).toFixed(2)}"`,
        `"${(filteredTotals.grandTotalPaise / 100).toFixed(2)}"`,
        '""'
      ].join(','));

      lines.push('');
      lines.push('"© AESCION Billing Software. All Rights Reserved."');

      const csvContent = BOM + lines.join('\r\n');
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const downloadAnchor = document.createElement('a');
      const filename = `AESCION_SalesReport_${formatDateDMY(dateFrom)}_to_${formatDateDMY(dateTo)}.csv`;
      downloadAnchor.setAttribute('href', url);
      downloadAnchor.setAttribute('download', filename);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      document.body.removeChild(downloadAnchor);
      URL.revokeObjectURL(url);

      toast.success(`Sales report exported to Downloads folder successfully!`);
    } catch (err: any) {
      console.error('Export error:', err);
      toast.error('Failed to export sales report');
    } finally {
      setIsExporting(false);
    }
  };

  // Open Bill Details
  const handleOpenDetail = async (billId: number) => {
    setIsDetailLoading(true);
    setIsDetailOpen(true);
    try {
      const detail = await api.getBillDetail(billId);
      setSelectedBillDetail(detail);
    } catch {
      toast.error('Failed to load bill details');
      setIsDetailOpen(false);
    } finally {
      setIsDetailLoading(false);
    }
  };

  // Filter bills based on search, status, and payment
  const filteredBills = useMemo(() => {
    return bills.filter((b) => {
      // Search filter
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase().trim();
        const numMatch = String(b.bill_number).includes(q);
        const staffMatch = (b.user_name || '').toLowerCase().includes(q);
        if (!numMatch && !staffMatch) return false;
      }
      // Status filter
      if (statusFilter && b.status !== statusFilter) {
        return false;
      }
      // Payment filter
      if (paymentFilter && (b.payment_method || 'cash').toLowerCase() !== paymentFilter.toLowerCase()) {
        return false;
      }
      return true;
    });
  }, [bills, searchQuery, statusFilter, paymentFilter]);

  // Aggregate Totals for Filtered Records
  const filteredTotals = useMemo(() => {
    return filteredBills.reduce(
      (acc, b) => {
        // Exclude cancelled and voided bills from net revenue sum
        const isExcluded = b.status === 'cancelled' || b.status === 'voided';
        return {
          count: acc.count + 1,
          subtotalPaise: acc.subtotalPaise + (isExcluded ? 0 : b.subtotal_paise),
          discountPaise: acc.discountPaise + (isExcluded ? 0 : b.discount_amount_paise),
          gstPaise: acc.gstPaise + (isExcluded ? 0 : b.gst_total_paise),
          grandTotalPaise: acc.grandTotalPaise + (isExcluded ? 0 : b.grand_total_paise),
        };
      },
      { count: 0, subtotalPaise: 0, discountPaise: 0, gstPaise: 0, grandTotalPaise: 0 }
    );
  }, [filteredBills]);

  // Helper for Payment Icons
  const getPaymentIcon = (method?: string) => {
    switch ((method || 'cash').toLowerCase()) {
      case 'upi':
        return <QrCode className="w-3.5 h-3.5 text-purple-600 inline mr-1" />;
      case 'card':
        return <CreditCard className="w-3.5 h-3.5 text-blue-600 inline mr-1" />;
      case 'upi_cash':
        return <Banknote className="w-3.5 h-3.5 text-emerald-600 inline mr-1" />;
      default:
        return <Banknote className="w-3.5 h-3.5 text-emerald-600 inline mr-1" />;
    }
  };

  // Helper for Status Badge
  const getStatusBadge = (status: string, voidReason?: string) => {
    switch (status) {
      case 'completed':
        return <span className="badge badge-success font-semibold">Completed</span>;
      case 'returned':
        return (
          <span
            className="badge badge-warning font-semibold cursor-help"
            title={voidReason || 'Partially Returned'}
          >
            Returned
          </span>
        );
      case 'cancelled':
        return (
          <span
            className="badge badge-neutral font-semibold cursor-help"
            title={voidReason || 'All items returned / Cancelled'}
          >
            Cancelled
          </span>
        );
      case 'voided':
        return (
          <span
            className="badge badge-danger font-semibold cursor-help"
            title={voidReason || 'Voided Transaction'}
          >
            Voided
          </span>
        );
      default:
        return <span className="badge badge-neutral font-semibold">{status}</span>;
    }
  };

  const isFiltering = !!(searchQuery || statusFilter || paymentFilter || dateFrom !== todayStr || dateTo !== todayStr);

  return (
    <div className="flex flex-col h-full overflow-hidden bg-surface-50">
      <Header
        title="Sales & Financial Reports"
        subtitle="Itemized revenue breakdown, audit registers, and financial tallies"
        actions={
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={async () => {
                try {
                  await api.openDownloadsFolder();
                  toast.success('Opened Downloads folder in Explorer');
                } catch {
                  toast.error('Could not open Downloads folder');
                }
              }}
              className="btn-secondary flex items-center gap-1.5 text-xs font-semibold shadow-sm cursor-pointer"
              title="Open Downloads folder where exported Excel reports are saved"
            >
              <FolderOpen className="w-3.5 h-3.5 text-amber-600" />
              <span>Open Downloads</span>
            </button>
            <button
              type="button"
              onClick={handleExportExcel}
              disabled={isExporting || bills.length === 0}
              className="btn-primary flex items-center gap-1.5 text-xs font-semibold shadow-sm cursor-pointer disabled:opacity-50"
            >
              <Download className="w-3.5 h-3.5" />
              <span>{isExporting ? 'Exporting...' : 'Export Excel (.xlsx)'}</span>
            </button>
          </div>
        }
      />

      <div className="p-6 overflow-y-auto flex-1 space-y-4">
        {/* Filters Toolbar - Single Row */}
        <div className="card px-3.5 py-2.5 bg-white border border-surface-200 rounded-xl shadow-xs flex items-center gap-2.5">
          {/* From Date */}
          <div className="flex items-center gap-1.5 bg-surface-50 px-2.5 py-1.5 rounded-lg border border-surface-200 text-xs shrink-0">
            <Calendar className="w-3.5 h-3.5 text-surface-400" />
            <span className="font-semibold text-surface-600">From:</span>
            <input
              type="date"
              value={dateFrom}
              max={todayStr}
              onChange={(e) => {
                const newFrom = e.target.value;
                setDateFrom(newFrom);
                if (newFrom > dateTo) setDateTo(newFrom);
              }}
              className="bg-transparent border-0 text-xs font-mono font-semibold text-surface-900 p-0 focus:ring-0 cursor-pointer"
              title="From date"
            />
          </div>

          {/* To Date */}
          <div className="flex items-center gap-1.5 bg-surface-50 px-2.5 py-1.5 rounded-lg border border-surface-200 text-xs shrink-0">
            <Calendar className="w-3.5 h-3.5 text-surface-400" />
            <span className="font-semibold text-surface-600">To:</span>
            <input
              type="date"
              value={dateTo}
              min={dateFrom}
              max={todayStr}
              onChange={(e) => setDateTo(e.target.value)}
              className="bg-transparent border-0 text-xs font-mono font-semibold text-surface-900 p-0 focus:ring-0 cursor-pointer"
              title="To date"
            />
          </div>

          {/* Search Input */}
          <div className="relative flex-1 min-w-[200px]">
            <Search className="w-3.5 h-3.5 text-surface-400 absolute left-3 top-2.5" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by Bill # or Cashier Name..."
              className="form-input pl-8 h-8 text-xs w-full"
            />
            {searchQuery && (
              <button
                type="button"
                onClick={() => setSearchQuery('')}
                className="absolute right-2.5 top-2 text-2xs text-surface-400 hover:text-surface-600 font-semibold cursor-pointer"
              >
                Clear
              </button>
            )}
          </div>

          {/* Status Filter */}
          <CustomSelect
            value={statusFilter}
            onChange={setStatusFilter}
            options={[
              { value: '', label: 'All Statuses' },
              { value: 'completed', label: 'Completed' },
              { value: 'returned', label: 'Returned (Partial)' },
              { value: 'cancelled', label: 'Cancelled (Full Return)' },
              { value: 'voided', label: 'Voided' },
            ]}
            size="sm"
            buttonClassName="w-36 h-8 text-xs font-medium rounded-lg"
          />

          {/* Payment Filter */}
          <CustomSelect
            value={paymentFilter}
            onChange={setPaymentFilter}
            options={[
              { value: '', label: 'All Payments' },
              { value: 'cash', label: 'Cash' },
              { value: 'upi', label: 'UPI / QR' },
              { value: 'card', label: 'Card' },
              { value: 'upi_cash', label: 'Split (UPI + Cash)' },
            ]}
            size="sm"
            buttonClassName="w-40 h-8 text-xs font-medium rounded-lg"
          />

          {/* Reset Filters */}
          {isFiltering && (
            <button
              type="button"
              onClick={() => {
                setDateFrom(todayStr);
                setDateTo(todayStr);
                setSearchQuery('');
                setStatusFilter('');
                setPaymentFilter('');
              }}
              className="btn-secondary h-8 px-2.5 text-xs flex items-center gap-1 text-surface-600 hover:text-surface-900 cursor-pointer shrink-0"
              title="Reset all filters"
            >
              <RotateCcw className="w-3 h-3" />
              <span>Reset</span>
            </button>
          )}
        </div>

        {/* Executive KPI Metric Cards */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
          {/* Net Sales */}
          <div className="card p-3.5 bg-white border border-surface-200 rounded-xl shadow-xs">
            <div className="flex items-center justify-between text-xs text-surface-600 uppercase font-bold tracking-wider">
              <span>Net Revenue</span>
              <TrendingUp className="w-4 h-4 text-emerald-800" />
            </div>
            <div className="text-xl font-black font-mono text-emerald-950 mt-1">
              {formatCurrency(stats?.total_sales_paise || 0)}
            </div>
            <div className="text-xs text-surface-600 mt-0.5 font-medium">
              Net realized sales
            </div>
          </div>

          {/* Bills Count */}
          <div className="card p-3.5 bg-white border border-surface-200 rounded-xl shadow-xs">
            <div className="flex items-center justify-between text-xs text-surface-600 uppercase font-bold tracking-wider">
              <span>Total Bills</span>
              <Receipt className="w-4 h-4 text-primary-800" />
            </div>
            <div className="text-xl font-black font-mono text-surface-950 mt-1">
              {stats?.total_bills || 0}
            </div>
            <div className="text-xs text-surface-600 mt-0.5 font-medium">
              Transactions
            </div>
          </div>

          {/* Items Sold */}
          <div className="card p-3.5 bg-white border border-surface-200 rounded-xl shadow-xs">
            <div className="flex items-center justify-between text-xs text-surface-600 uppercase font-bold tracking-wider">
              <span>Items Sold</span>
              <ShoppingBag className="w-4 h-4 text-indigo-800" />
            </div>
            <div className="text-xl font-black font-mono text-surface-950 mt-1">
              {stats?.total_items_sold || 0}
            </div>
            <div className="text-xs text-surface-600 mt-0.5 font-medium">
              Units across all bills
            </div>
          </div>

          {/* GST Total */}
          <div className="card p-3.5 bg-white border border-surface-200 rounded-xl shadow-xs">
            <div className="flex items-center justify-between text-xs text-surface-600 uppercase font-bold tracking-wider">
              <span>GST / Taxes</span>
              <Percent className="w-4 h-4 text-blue-800" />
            </div>
            <div className="text-xl font-black font-mono text-blue-950 mt-1">
              {formatCurrency(stats?.total_gst_paise || 0)}
            </div>
            <div className="text-xs text-surface-600 mt-0.5 font-medium">
              Tax output collected
            </div>
          </div>

          {/* Discounts */}
          <div className="card p-3.5 bg-white border border-surface-200 rounded-xl shadow-xs">
            <div className="flex items-center justify-between text-xs text-surface-600 uppercase font-bold tracking-wider">
              <span>Discounts</span>
              <Tag className="w-4 h-4 text-amber-800" />
            </div>
            <div className="text-xl font-black font-mono text-amber-950 mt-1">
              {formatCurrency(stats?.total_discount_paise || 0)}
            </div>
            <div className="text-xs text-surface-600 mt-0.5 font-medium">
              Discounts granted
            </div>
          </div>

          {/* Avg Bill */}
          <div className="card p-3.5 bg-white border border-surface-200 rounded-xl shadow-xs">
            <div className="flex items-center justify-between text-xs text-surface-600 uppercase font-bold tracking-wider">
              <span>Avg Bill</span>
              <Banknote className="w-4 h-4 text-primary-800" />
            </div>
            <div className="text-xl font-black font-mono text-surface-950 mt-1">
              {formatCurrency(stats?.avg_bill_paise || 0)}
            </div>
            <div className="text-xs text-surface-600 mt-0.5 font-medium">
              Average ticket size
            </div>
          </div>
        </div>

        {/* Payment Methods Breakdown Strip */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {/* Cash */}
          <div className="card p-3 bg-white border border-surface-200 rounded-xl flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-10 h-10 rounded-lg bg-emerald-100 text-emerald-950 flex items-center justify-center border border-emerald-300 flex-shrink-0 shadow-2xs">
                <Banknote className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs uppercase font-bold text-surface-600">Cash Received</div>
                <div className="text-base font-bold font-mono text-surface-950">
                  {formatCurrency(stats?.cash_sales_paise || 0)}
                </div>
              </div>
            </div>
            <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded bg-surface-100 text-surface-800 border border-surface-200">
              {stats?.total_sales_paise
                ? `${Math.round(((stats.cash_sales_paise || 0) / stats.total_sales_paise) * 100)}%`
                : '0%'}
            </span>
          </div>

          {/* UPI */}
          <div className="card p-3 bg-white border border-surface-200 rounded-xl flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-10 h-10 rounded-lg bg-purple-100 text-purple-950 flex items-center justify-center border border-purple-300 flex-shrink-0 shadow-2xs">
                <QrCode className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs uppercase font-bold text-surface-600">UPI / QR Digital</div>
                <div className="text-base font-bold font-mono text-surface-950">
                  {formatCurrency(stats?.upi_sales_paise || 0)}
                </div>
              </div>
            </div>
            <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded bg-surface-100 text-surface-800 border border-surface-200">
              {stats?.total_sales_paise
                ? `${Math.round(((stats.upi_sales_paise || 0) / stats.total_sales_paise) * 100)}%`
                : '0%'}
            </span>
          </div>

          {/* Card */}
          <div className="card p-3 bg-white border border-surface-200 rounded-xl flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-10 h-10 rounded-lg bg-blue-100 text-blue-950 flex items-center justify-center border border-blue-300 flex-shrink-0 shadow-2xs">
                <CreditCard className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs uppercase font-bold text-surface-600">Card Payments</div>
                <div className="text-base font-bold font-mono text-surface-950">
                  {formatCurrency(stats?.card_sales_paise || 0)}
                </div>
              </div>
            </div>
            <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded bg-surface-100 text-surface-800 border border-surface-200">
              {stats?.total_sales_paise
                ? `${Math.round(((stats.card_sales_paise || 0) / stats.total_sales_paise) * 100)}%`
                : '0%'}
            </span>
          </div>
        </div>

        {/* Detailed Transactions Table */}
        <div className="card overflow-hidden bg-white border border-surface-200 rounded-xl shadow-xs">
          <div className="card-header bg-surface-50/50 py-3 px-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-surface-800 uppercase tracking-wide">
                Transactions Register
              </span>
              <span className="badge badge-neutral text-2xs font-mono font-bold">
                {filteredBills.length} records
              </span>
            </div>
            <div className="text-xs font-mono text-surface-600">
              Filtered Total: <strong className="text-surface-900 font-bold">{formatCurrency(filteredTotals.grandTotalPaise)}</strong>
            </div>
          </div>

          <div className="table-container">
            <table className="table w-full">
              <thead>
                <tr>
                  <th className="w-28 text-left">Bill #</th>
                  <th className="w-36 text-left">Date & Time</th>
                  <th className="w-32 text-left">Cashier</th>
                  <th className="w-28 text-left">Payment</th>
                  <th className="w-28 text-right">Subtotal</th>
                  <th className="w-24 text-right">Discount</th>
                  <th className="w-24 text-right">GST</th>
                  <th className="w-32 text-right">Grand Total</th>
                  <th className="w-28 text-center">Status</th>
                  <th className="w-20 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-100">
                {isLoading ? (
                  <tr>
                    <td colSpan={10} className="text-center py-12 text-surface-400">
                      <div className="spinner mx-auto mb-2" />
                      Loading sales report records...
                    </td>
                  </tr>
                ) : filteredBills.length === 0 ? (
                  <tr>
                    <td colSpan={10} className="text-center py-12 text-surface-400 text-xs">
                      No billing records match the selected date or search criteria.
                    </td>
                  </tr>
                ) : (
                  filteredBills.map((b) => (
                    <tr
                      key={b.id}
                      className={`hover:bg-surface-50/80 transition-colors ${
                        b.status === 'voided'
                          ? 'opacity-60 bg-red-50/20'
                          : b.status === 'cancelled'
                          ? 'opacity-70 bg-surface-100/30'
                          : b.status === 'returned'
                          ? 'bg-amber-50/20'
                          : ''
                      }`}
                    >
                      <td className="font-mono font-bold text-primary-700 text-xs whitespace-nowrap">
                        Bill: {String(b.bill_number).padStart(5, '0')}
                      </td>
                      <td className="text-xs text-surface-700 font-mono">
                        <div>{formatDateDMY(b.business_date)}</div>
                        <div className="text-2xs text-surface-400">{b.bill_time}</div>
                      </td>
                      <td className="text-xs text-surface-800 font-medium">
                        {b.user_name || 'Staff'}
                      </td>
                      <td className="text-center whitespace-nowrap">
                        <span className="badge badge-neutral font-semibold text-2xs inline-flex items-center gap-1">
                          {getPaymentIcon(b.payment_method)}
                          <span>{formatPaymentMethod(b.payment_method)}</span>
                        </span>
                      </td>
                      <td className="font-mono text-xs text-surface-600 text-right">
                        {formatCurrency(b.subtotal_paise)}
                      </td>
                      <td className="font-mono text-xs text-red-600 text-right">
                        {b.discount_amount_paise > 0
                          ? `-${formatCurrency(b.discount_amount_paise)}`
                          : '—'}
                      </td>
                      <td className="font-mono text-xs text-surface-600 text-right">
                        {b.gst_total_paise > 0
                          ? formatCurrency(b.gst_total_paise)
                          : '—'}
                      </td>
                      <td className="text-right font-mono font-bold text-xs text-surface-900">
                        {formatCurrency(b.grand_total_paise)}
                      </td>
                      <td className="text-center">
                        {getStatusBadge(b.status, b.void_reason)}
                      </td>
                      <td className="text-right">
                        <button
                          type="button"
                          onClick={() => handleOpenDetail(b.id)}
                          className="p-1.5 text-surface-400 hover:text-primary-600 hover:bg-primary-50 rounded-md transition-colors cursor-pointer"
                          title="View Bill Details & Receipt"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>

              {/* Table Footer: Tally Grand Totals */}
              {filteredBills.length > 0 && (
                <tfoot>
                  <tr className="bg-surface-100/90 font-bold border-t-2 border-surface-300 text-xs">
                    <td colSpan={4} className="text-surface-800 uppercase tracking-wider px-4 py-3">
                      Total Summary ({filteredTotals.count} Bills)
                    </td>
                    <td className="font-mono text-right text-surface-700 px-4 py-3">
                      {formatCurrency(filteredTotals.subtotalPaise)}
                    </td>
                    <td className="font-mono text-right text-red-600 px-4 py-3">
                      {filteredTotals.discountPaise > 0 ? `-${formatCurrency(filteredTotals.discountPaise)}` : formatCurrency(0)}
                    </td>
                    <td className="font-mono text-right text-surface-700 px-4 py-3">
                      {formatCurrency(filteredTotals.gstPaise)}
                    </td>
                    <td className="font-mono text-right text-primary-950 font-extrabold text-sm px-4 py-3">
                      {formatCurrency(filteredTotals.grandTotalPaise)}
                    </td>
                    <td colSpan={2} />
                  </tr>
                </tfoot>
              )}
            </table>
          </div>
        </div>
      </div>

      {/* Bill Details Modal — Full Landscape Width */}
      <Modal
        isOpen={isDetailOpen}
        onClose={() => setIsDetailOpen(false)}
        title={
          selectedBillDetail
            ? `Bill: ${String(selectedBillDetail.bill.bill_number).padStart(5, '0')} Detailed Breakdown`
            : 'Loading Bill...'
        }
        maxWidth="5xl"
        closeOnBackdropClick={false}
        footer={
          selectedBillDetail && (
            <div className="flex items-center justify-between w-full">
              <button
                type="button"
                onClick={() => setIsDetailOpen(false)}
                className="btn-secondary text-xs px-3 py-1.5"
              >
                Close
              </button>
              <button
                type="button"
                onClick={() => setIsPrintModalOpen(true)}
                className="btn-primary text-xs font-bold flex items-center gap-1.5 px-4 py-1.5"
                title="Print receipt"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print Bill Receipt</span>
              </button>
            </div>
          )
        }
      >
        {isDetailLoading || !selectedBillDetail ? (
          <div className="py-8 text-center text-surface-400">
            <div className="spinner mx-auto mb-2" />
            Loading bill details...
          </div>
        ) : (
          <div className="space-y-4">
            {/* Header Strip */}
            <div className="p-3 rounded-lg bg-surface-50 border border-surface-200 grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
              <div>
                <span className="text-surface-500">Bill Number:</span>
                <div className="font-mono font-bold text-surface-900 whitespace-nowrap">
                  Bill: {String(selectedBillDetail.bill.bill_number).padStart(5, '0')}
                </div>
              </div>
              <div>
                <span className="text-surface-500">Date & Time:</span>
                <div className="font-mono text-surface-900">
                  {formatDateDMY(selectedBillDetail.bill.business_date)} {selectedBillDetail.bill.bill_time}
                </div>
              </div>
              <div>
                <span className="text-surface-500">Staff Cashier:</span>
                <div className="font-medium text-surface-900">
                  {selectedBillDetail.bill.user_name || 'Staff'}
                </div>
              </div>
              <div>
                <span className="text-surface-500">Status:</span>
                <div className="mt-0.5">
                  {getStatusBadge(
                    selectedBillDetail.bill.status,
                    selectedBillDetail.bill.void_reason
                  )}
                </div>
              </div>
            </div>

            {/* Returned Items Section (Task 4: If return is done, show returned product name & how many qty returned) */}
            {((selectedBillDetail.returned_items && selectedBillDetail.returned_items.length > 0) ||
              selectedBillDetail.items.some((it) => (it.returned_quantity && it.returned_quantity > 0) || it.quantity === 0) ||
              selectedBillDetail.bill.status === 'returned' ||
              selectedBillDetail.bill.status === 'cancelled') && (
              <div className="space-y-2 p-3 bg-amber-50/70 rounded-xl border border-amber-200">
                <div className="flex items-center gap-2 text-amber-900 font-bold text-xs uppercase tracking-wide">
                  <RotateCcw className="w-4 h-4 text-amber-700" />
                  <span>Returned Products & Quantities</span>
                  <span className="ml-auto text-2xs font-mono font-bold text-amber-800 bg-amber-100 px-2 py-0.5 rounded-full border border-amber-300">
                    {selectedBillDetail.returned_items && selectedBillDetail.returned_items.length > 0
                      ? `${selectedBillDetail.returned_items.length} ${selectedBillDetail.returned_items.length === 1 ? 'Product Returned' : 'Products Returned'}`
                      : 'Returns Processed'}
                  </span>
                </div>

                <div className="border border-amber-200 rounded-lg overflow-hidden bg-white shadow-2xs">
                  <table className="table w-full text-xs">
                    <thead className="bg-amber-100/60 text-amber-950 font-bold">
                      <tr>
                        <th className="py-2 text-left">Returned Product</th>
                        <th className="py-2 text-center w-28">Returned Qty</th>
                        <th className="py-2 text-right w-28">Unit Price</th>
                        <th className="py-2 text-right w-28">Refund Amount</th>
                        <th className="py-2 text-left w-36">Return Reason</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-amber-100">
                      {selectedBillDetail.returned_items && selectedBillDetail.returned_items.length > 0 ? (
                        selectedBillDetail.returned_items.map((ret, idx) => (
                          <tr key={ret.id || idx} className="hover:bg-amber-50/40">
                            <td className="font-semibold text-surface-900 whitespace-nowrap">
                              <span className="font-bold">{ret.product_name}</span>
                              {ret.product_code && (
                                <span className="text-3xs text-surface-400 font-mono ml-1.5">({ret.product_code})</span>
                              )}
                            </td>
                            <td className="text-center font-mono">
                              <span className="inline-flex items-center font-bold px-2 py-0.5 rounded bg-amber-100 text-amber-900 border border-amber-300">
                                {ret.quantity} {ret.quantity === 1 ? 'Unit' : 'Units'}
                              </span>
                            </td>
                            <td className="text-right font-mono text-surface-700">
                              {formatCurrency(ret.unit_price_paise)}
                            </td>
                            <td className="text-right font-mono font-bold text-red-600">
                              -{formatCurrency(ret.line_total_paise || ret.unit_price_paise * ret.quantity)}
                            </td>
                            <td className="text-surface-700 text-2xs italic whitespace-nowrap">
                              <span>"{ret.reason || 'Customer Return'}"</span>
                              {ret.returned_at && (
                                <span className="text-3xs text-surface-400 not-italic font-mono ml-1.5">
                                  [{ret.returned_at}]
                                </span>
                              )}
                            </td>
                          </tr>
                        ))
                      ) : (
                        // Fallback synthesized from items
                        selectedBillDetail.items
                          .filter((it) => (it.returned_quantity && it.returned_quantity > 0) || it.quantity === 0)
                          .map((it) => {
                            const retQty = it.returned_quantity || 1;
                            const refund = it.unit_price_paise * retQty;
                            return (
                              <tr key={it.id} className="hover:bg-amber-50/40">
                                <td className="font-semibold text-surface-900 whitespace-nowrap">
                                  <span className="font-bold">{it.product_name_snapshot || (it as any).product_name || 'Item'}</span>
                                  <span className="text-3xs text-surface-400 font-mono ml-1.5">
                                    ({it.product_code_snapshot || 'N/A'})
                                  </span>
                                </td>
                                <td className="text-center font-mono">
                                  <span className="inline-flex items-center font-bold px-2 py-0.5 rounded bg-amber-100 text-amber-900 border border-amber-300">
                                    {retQty} {retQty === 1 ? 'Unit' : 'Units'}
                                  </span>
                                </td>
                                <td className="text-right font-mono text-surface-700">
                                  {formatCurrency(it.unit_price_paise)}
                                </td>
                                <td className="text-right font-mono font-bold text-red-600">
                                  -{formatCurrency(refund)}
                                </td>
                                <td className="text-surface-700 text-2xs italic whitespace-nowrap">
                                  "{selectedBillDetail.bill.void_reason || 'Customer Return'}"
                                </td>
                              </tr>
                            );
                          })
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Items Table */}
            <div>
              <div className="text-xs font-bold text-surface-700 uppercase tracking-wide mb-1.5 flex items-center justify-between">
                <span>Purchased Line Items</span>
                <span className="text-3xs text-surface-400 font-normal lowercase">current remaining bill items</span>
              </div>
              <div className="border border-surface-200 rounded-lg overflow-hidden">
                <table className="table w-full">
                  <thead>
                    <tr>
                      <th className="whitespace-nowrap">Product</th>
                      <th className="whitespace-nowrap">Category</th>
                      <th className="text-right whitespace-nowrap">Unit Price</th>
                      <th className="text-center whitespace-nowrap">Active Qty</th>
                      <th className="text-right whitespace-nowrap">Line Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {selectedBillDetail.items.map((it) => (
                      <tr key={it.id}>
                        <td className="font-medium text-surface-900 text-xs whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <span className="font-semibold text-surface-950">
                              {it.product_name_snapshot || (it as any).product_name || (it as any).name || 'Item'}
                            </span>
                            <span className="text-2xs text-surface-400 font-mono">
                              ({it.product_code_snapshot || (it as any).product_code || (it as any).code || 'N/A'})
                            </span>
                            {(it.returned_quantity && it.returned_quantity > 0) ? (
                              <span className="inline-flex text-3xs font-bold px-1.5 py-0.5 rounded bg-amber-100 text-amber-900 border border-amber-300">
                                {it.returned_quantity} Returned
                              </span>
                            ) : it.quantity === 0 ? (
                              <span className="inline-flex text-3xs font-semibold px-1.5 py-0.5 rounded bg-red-100 text-red-800 border border-red-300">
                                Fully Returned
                              </span>
                            ) : null}
                          </div>
                        </td>
                        <td className="text-surface-500 text-xs">
                          {it.category_name_snapshot || (it as any).category_name || (it as any).category || 'General'}
                        </td>
                        <td className="text-right font-mono text-xs">
                          {formatCurrency(it.unit_price_paise)}
                        </td>
                        <td className="text-center font-mono font-bold text-xs">
                          {it.quantity}
                        </td>
                        <td className="text-right font-mono font-bold text-surface-900 text-xs">
                          {formatCurrency(it.line_total_paise)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Bill Summary */}
            <div className="p-3 rounded-lg bg-surface-50 border border-surface-200 space-y-1.5 text-xs">
              <div className="flex justify-between text-surface-600">
                <span>Subtotal:</span>
                <span className="font-mono">
                  {formatCurrency(selectedBillDetail.bill.subtotal_paise)}
                </span>
              </div>
              {selectedBillDetail.bill.discount_amount_paise > 0 && (
                <div className="flex justify-between text-red-600 font-medium">
                  <span>Discount:</span>
                  <span className="font-mono">
                    -{formatCurrency(selectedBillDetail.bill.discount_amount_paise)}
                  </span>
                </div>
              )}
              {selectedBillDetail.bill.gst_total_paise > 0 && (
                <div className="flex justify-between text-surface-600">
                  <span>GST:</span>
                  <span className="font-mono">
                    {formatCurrency(selectedBillDetail.bill.gst_total_paise)}
                  </span>
                </div>
              )}
              <div className="flex justify-between pt-1 border-t border-surface-200 text-sm font-bold text-surface-900">
                <span>Grand Total:</span>
                <span className="font-mono text-primary-700 font-extrabold">
                  {formatCurrency(selectedBillDetail.bill.grand_total_paise)}
                </span>
              </div>
            </div>

            {/* Notes if voided or returned */}
            {selectedBillDetail.bill.void_reason && (
              <div
                className={`p-2.5 rounded-lg border text-xs ${
                  selectedBillDetail.bill.status === 'voided'
                    ? 'bg-red-50 border-red-200 text-red-800'
                    : selectedBillDetail.bill.status === 'cancelled'
                    ? 'bg-slate-50 border-slate-200 text-slate-800'
                    : 'bg-amber-50 border-amber-200 text-amber-800'
                }`}
              >
                <span className="font-bold uppercase">Note / Reason: </span>
                <span>{selectedBillDetail.bill.void_reason}</span>
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* Bill Receipt Print Modal */}
      {selectedBillDetail && (
        <ReceiptPrintModal
          isOpen={isPrintModalOpen}
          onClose={() => setIsPrintModalOpen(false)}
          title={`Print Bill #${selectedBillDetail.bill.bill_number}`}
          billData={{
            billNumber: selectedBillDetail.bill.bill_number,
            billUuid: selectedBillDetail.bill.bill_uuid,
            businessDate: selectedBillDetail.bill.business_date,
            billTime: selectedBillDetail.bill.bill_time,
            cashierName: selectedBillDetail.bill.user_name || 'Staff',
            items: selectedBillDetail.items.map((it) => ({
              product_name: it.product_name_snapshot,
              product_code: it.product_code_snapshot,
              quantity: it.quantity,
              unit_price_paise: it.unit_price_paise,
              line_total_paise: it.line_total_paise,
            })),
            subtotalPaise: selectedBillDetail.bill.subtotal_paise,
            discountAmountPaise: selectedBillDetail.bill.discount_amount_paise,
            discountType: selectedBillDetail.bill.discount_type,
            discountValue: selectedBillDetail.bill.discount_value_x100 / 100,
            gstTotalPaise: selectedBillDetail.bill.gst_total_paise,
            grandTotalPaise: selectedBillDetail.bill.grand_total_paise,
            paymentMethod: selectedBillDetail.payment?.payment_method || selectedBillDetail.bill.payment_method || 'cash',
            cashAmountPaise: selectedBillDetail.payment?.cash_amount_paise,
            upiAmountPaise: selectedBillDetail.payment?.upi_amount_paise,
            tenderedCashPaise: selectedBillDetail.payment?.cash_amount_paise,
            changeDuePaise: (selectedBillDetail.payment?.cash_amount_paise || 0) > selectedBillDetail.bill.grand_total_paise
              ? (selectedBillDetail.payment?.cash_amount_paise || 0) - selectedBillDetail.bill.grand_total_paise
              : 0,
          }}
        />
      )}
    </div>
  );
};
